//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientSchedule.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClientSchedule.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an appointment starting soon:
        ///
        ///Customer: {0}
        ///Title: {1}
        ///Type: {2}
        ///Starts: {3}
        ///.
        /// </summary>
        internal static string Alert_UpcomingApptBody {
            get {
                return ResourceManager.GetString("Alert_UpcomingApptBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Alert.
        /// </summary>
        internal static string Alert_UpcomingApptTitle {
            get {
                return ResourceManager.GetString("Alert_UpcomingApptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Appt_Customer {
            get {
                return ResourceManager.GetString("Appt_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Appt_Delete {
            get {
                return ResourceManager.GetString("Appt_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed.
        /// </summary>
        internal static string Appt_DeleteFailed {
            get {
                return ResourceManager.GetString("Appt_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Appt_Description {
            get {
                return ResourceManager.GetString("Appt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Appt_End {
            get {
                return ResourceManager.GetString("Appt_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Appt_Location {
            get {
                return ResourceManager.GetString("Appt_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        internal static string Appt_SaveFailed {
            get {
                return ResourceManager.GetString("Appt_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Appt_Start {
            get {
                return ResourceManager.GetString("Appt_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Appt_Title {
            get {
                return ResourceManager.GetString("Appt_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Appt_Type {
            get {
                return ResourceManager.GetString("Appt_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments must be scheduled Monday–Friday, 9:00 AM–5:00 PM Eastern Time..
        /// </summary>
        internal static string Appt_Validation_BusinessHours {
            get {
                return ResourceManager.GetString("Appt_Validation_BusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time must be after start time..
        /// </summary>
        internal static string Appt_Validation_EndAfterStart {
            get {
                return ResourceManager.GetString("Appt_Validation_EndAfterStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This appointment overlaps with an existing appointment..
        /// </summary>
        internal static string Appt_Validation_Overlap {
            get {
                return ResourceManager.GetString("Appt_Validation_Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer, Title, Type, Start, and End are required..
        /// </summary>
        internal static string Appt_Validation_Required {
            get {
                return ResourceManager.GetString("Appt_Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments must be within a single business day (Eastern Time)..
        /// </summary>
        internal static string Appt_Validation_SameDay {
            get {
                return ResourceManager.GetString("Appt_Validation_SameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ApptEdit_Title_Add {
            get {
                return ResourceManager.GetString("ApptEdit_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ApptEdit_Title_Edit {
            get {
                return ResourceManager.GetString("ApptEdit_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string Appy_Modify {
            get {
                return ResourceManager.GetString("Appy_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string Col_ApptCustomer {
            get {
                return ResourceManager.GetString("Col_ApptCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string Col_ApptEnd {
            get {
                return ResourceManager.GetString("Col_ApptEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Col_ApptId {
            get {
                return ResourceManager.GetString("Col_ApptId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Col_ApptStart {
            get {
                return ResourceManager.GetString("Col_ApptStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Col_ApptTitle {
            get {
                return ResourceManager.GetString("Col_ApptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Col_ApptType {
            get {
                return ResourceManager.GetString("Col_ApptType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this appointment?.
        /// </summary>
        internal static string ConfirmDeleteAppt {
            get {
                return ResourceManager.GetString("ConfirmDeleteAppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this customer?.
        /// </summary>
        internal static string ConfirmDeleteCustomer {
            get {
                return ResourceManager.GetString("ConfirmDeleteCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Customer_Address {
            get {
                return ResourceManager.GetString("Customer_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        internal static string Customer_Address2 {
            get {
                return ResourceManager.GetString("Customer_Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Customer_City {
            get {
                return ResourceManager.GetString("Customer_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Customer_Country {
            get {
                return ResourceManager.GetString("Customer_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this customer because they have existing appointments..
        /// </summary>
        internal static string Customer_Delete_HasAppointments {
            get {
                return ResourceManager.GetString("Customer_Delete_HasAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string Customer_Name {
            get {
                return ResourceManager.GetString("Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string Customer_Phone {
            get {
                return ResourceManager.GetString("Customer_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string Customer_Postal {
            get {
                return ResourceManager.GetString("Customer_Postal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a city..
        /// </summary>
        internal static string Customer_Validation_City {
            get {
                return ResourceManager.GetString("Customer_Validation_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a country..
        /// </summary>
        internal static string Customer_Validation_Country {
            get {
                return ResourceManager.GetString("Customer_Validation_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone must contain only digits and dashes..
        /// </summary>
        internal static string Customer_Validation_Phone {
            get {
                return ResourceManager.GetString("Customer_Validation_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name, Address, and Phone are required..
        /// </summary>
        internal static string Customer_Validation_Required {
            get {
                return ResourceManager.GetString("Customer_Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Customer.
        /// </summary>
        internal static string CustomerEdit_Title_Add {
            get {
                return ResourceManager.GetString("CustomerEdit_Title_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer.
        /// </summary>
        internal static string CustomerEdit_Title_Edit {
            get {
                return ResourceManager.GetString("CustomerEdit_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete failed..
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database error..
        /// </summary>
        internal static string Error_db {
            get {
                return ResourceManager.GetString("Error_db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a username and password..
        /// </summary>
        internal static string Error_EmptyFields {
            get {
                return ResourceManager.GetString("Error_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and password do not match..
        /// </summary>
        internal static string Error_InvalidCredentials {
            get {
                return ResourceManager.GetString("Error_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling System.
        /// </summary>
        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments per customer.
        /// </summary>
        internal static string Report_ByCustomer {
            get {
                return ResourceManager.GetString("Report_ByCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report failed..
        /// </summary>
        internal static string Report_Error {
            get {
                return ResourceManager.GetString("Report_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Report_Run {
            get {
                return ResourceManager.GetString("Report_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment types by month.
        /// </summary>
        internal static string Report_TypesByMonth {
            get {
                return ResourceManager.GetString("Report_TypesByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule for each user.
        /// </summary>
        internal static string Report_UserSchedules {
            get {
                return ResourceManager.GetString("Report_UserSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed..
        /// </summary>
        internal static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an appointment first..
        /// </summary>
        internal static string SelectApptFirst {
            get {
                return ResourceManager.GetString("SelectApptFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a customer first..
        /// </summary>
        internal static string SelectCustomerFirst {
            get {
                return ResourceManager.GetString("SelectCustomerFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string Tab_Appointments {
            get {
                return ResourceManager.GetString("Tab_Appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        internal static string Tab_Customers {
            get {
                return ResourceManager.GetString("Tab_Customers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Tab_Reports {
            get {
                return ResourceManager.GetString("Tab_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
